### ISSUE TITLE
Neobolt not compatible with Python 3.11

### ISSUE THREAD

**Issue by shawnmittal** [sckg/sckg#7]
Recommend removing neobolt from requirements.txt and upgrading neo4j version to 4.4. Neobolt has not been updated in 5 years and is no longer used by neo4j for bolt driver support. 

Bolt driver has been migrated to be a part of the Neo4j python package and 4.4 is currently functioning with build.py.

Also worth testing with neo4j==5.0.

**Comment by shawnmittal** [comment]
Can confirm build works with the latest neo4j python package v5.18.0

**Comment by jason-callaway** [comment]
Awesome! Thanks for confirming! I'll update main this weekend.
